services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9191:9090

  grafana:
    image: grafana/grafana:latest
    ports:
      - 3101:3000
    links:
      - prometheus